import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import {
  BOQController,
  CostEstimateController,
  EstimateAnalyticsController,
  EstimateTemplateController,
  EstimationCategoryController,
  LaborCostRateController,
  MarkupSettingController,
  MaterialCostRateController,
  OverheadCostController,
  PriceListController,
  PricingController,
  ResourceRateController,
  WorkflowStageSettingController,
  ReportScheduleController,
  EstimateCommentController,
} from './controllers';
import {
  BOQ,
  BOQItem,
  BOQTemplate,
  CostCategory,
  CostEstimate,
  CostEstimateItem,
  EquipmentRate,
  EstimateAccuracyRecord,
  EstimateApprovalWorkflow,
  EstimateTemplate,
  EstimateVersion,
  EstimatorPerformance,
  EstimationCategory,
  HistoricalBenchmark,
  LaborCostRate,
  LaborRateCard,
  MarkupRule,
  MarkupSetting,
  MaterialCostRate,
  MaterialRateCard,
  OverheadCost,
  PriceList,
  Pricing,
  ResourceRate,
  RiskAnalysis,
  SubcontractorRate,
  WinLossRecord,
  WorkflowStageSetting,
  ReportSchedule,
  EstimateComment,
} from './entities';
import {
  BOQService,
  CostEstimateService,
  EstimateAnalyticsService,
  EstimateTemplateService,
  EstimationCategoryService,
  LaborCostRateService,
  MarkupSettingService,
  MaterialCostRateService,
  OverheadCostService,
  PriceListService,
  PricingService,
  ResourceRateService,
  WorkflowStageSettingService,
  ReportScheduleService,
  EstimateCommentService,
} from './services';

@Module({
  imports: [
    TypeOrmModule.forFeature([
      // BOQ
      BOQ,
      BOQItem,
      BOQTemplate,
      // Cost Estimate
      CostEstimate,
      CostEstimateItem,
      // Pricing
      Pricing,
      MarkupRule,
      // Settings (orphan pages)
      PriceList,
      MarkupSetting,
      WorkflowStageSetting,
      // Resource Rates
      ResourceRate,
      MaterialRateCard,
      LaborRateCard,
      EquipmentRate,
      SubcontractorRate,
      // Templates & Settings
      EstimateTemplate,
      CostCategory,
      EstimateApprovalWorkflow,
      EstimateVersion,
      // Analytics
      WinLossRecord,
      EstimateAccuracyRecord,
      RiskAnalysis,
      EstimatorPerformance,
      HistoricalBenchmark,
      // Categories & Cost rates (orphan pages)
      EstimationCategory,
      LaborCostRate,
      MaterialCostRate,
      OverheadCost,
      // Report schedules & comments (orphan pages)
      ReportSchedule,
      EstimateComment,
    ]),
  ],
  controllers: [
    BOQController,
    CostEstimateController,
    EstimateAnalyticsController,
    EstimateTemplateController,
    EstimationCategoryController,
    LaborCostRateController,
    MaterialCostRateController,
    OverheadCostController,
    MarkupSettingController,
    PriceListController,
    PricingController,
    ResourceRateController,
    WorkflowStageSettingController,
    ReportScheduleController,
    EstimateCommentController,
  ],
  providers: [
    BOQService,
    CostEstimateService,
    EstimateAnalyticsService,
    EstimateTemplateService,
    EstimationCategoryService,
    LaborCostRateService,
    MaterialCostRateService,
    OverheadCostService,
    MarkupSettingService,
    PriceListService,
    PricingService,
    ResourceRateService,
    WorkflowStageSettingService,
    ReportScheduleService,
    EstimateCommentService,
  ],
  exports: [
    BOQService,
    CostEstimateService,
    EstimateAnalyticsService,
    EstimateTemplateService,
    EstimationCategoryService,
    LaborCostRateService,
    MaterialCostRateService,
    OverheadCostService,
    MarkupSettingService,
    PriceListService,
    PricingService,
    ResourceRateService,
    WorkflowStageSettingService,
    ReportScheduleService,
    EstimateCommentService,
  ],
})
export class EstimationModule {}
