import { Module, forwardRef } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { WorkflowModule } from '../workflow/workflow.module';
import { NotificationsModule } from '../notifications/notifications.module';
import { ProcurementReportSchedulerService } from './services/procurement-report-scheduler.service';
import { ProcurementAutomationEvaluatorService } from './services/procurement-automation-evaluator.service';
import {
  AuditTrailController,
  BomReceiptController,
  GoodsReceiptController,
  ProcurementBudgetController,
  ProcurementCategoryController,
  ProcurementNotificationController,
  ProcurementCalendarEventController,
  PurchaseInvoiceController,
  SavingsInitiativeController,
  VendorScorecardController,
  PurchaseOrderController,
  PurchaseRequisitionController,
  PurchaseReturnController,
  RFQController,
  RFQBidController,
  RFQTemplateController,
  SourcingIntegrationController,
  VendorCollaborationController,
  VendorContractController,
  VendorEvaluationController,
  VendorPerformanceAnalyticsController,
  VendorQuotationController,
  VendorController,
  SpendAnalysisController,
  ProcurementInsightsController,
  SourcingStrategyController,
  ProcurementReportTemplateController,
  ProcurementAutomationRuleController,
  ProcurementRiskAssessmentController,
  ProcurementComplianceRecordController,
  SupplierDiversityProgramController,
} from './controllers';
import {
  AuditTrail,
  BomReceipt,
  GoodsReceipt,
  GoodsReceiptItem,
  ProcurementBudget,
  ProcurementCalendarEvent,
  ProcurementCategory,
  ProcurementNotification,
  PurchaseInvoice,
  SavingsInitiative,
  VendorScorecard,
  PurchaseOrder,
  PurchaseOrderItem,
  PurchaseRequisition,
  PurchaseReturn,
  RFQ,
  RFQBid,
  RFQTemplate,
  SourcingRule,
  VendorContract,
  VendorEvaluation,
  VendorMessage,
  VendorQuotation,
  Vendor,
  SourcingStrategy,
  ProcurementReportTemplate,
  ProcurementAutomationRule,
  ProcurementRiskAssessment,
  ProcurementComplianceRecord,
  SupplierDiversityProgram,
} from './entities';
import {
  ApprovalThresholdSeederService,
  BomReceiptService,
  GoodsReceiptService,
  ProcurementBudgetService,
  ProcurementCalendarEventService,
  ProcurementCategoryService,
  ProcurementNotificationService,
  PurchaseInvoiceService,
  SavingsInitiativeService,
  VendorScorecardService,
  PurchaseOrderService,
  PurchaseRequisitionService,
  PurchaseReturnService,
  RFQService,
  RFQBidService,
  RFQTemplateService,
  VendorEvaluationService,
  VendorPerformanceAnalyticsService,
  VendorQuotationService,
  VendorService,
  SourcingStrategyService,
  ProcurementReportTemplateService,
  ProcurementAutomationRuleService,
  ProcurementRiskAssessmentService,
  ProcurementComplianceRecordService,
  SupplierDiversityProgramService,
} from './services';
import { ApprovalMatrixService } from './services/approval-matrix.service';
import { AuditTrailService } from './services/audit-trail.service';
import { ContractService } from './services/contract.service';
import { RFQPolicyService } from './services/rfq-policy.service';
import { SourcingIntegrationService } from './services/sourcing-integration.service';
import { SpendAnalysisService } from './services/spend-analysis.service';
import { ProcurementInsightsService } from './services/procurement-insights.service';
import { ThreeWayMatchingService } from './services/three-way-matching.service';
import { VendorCollaborationService } from './services/vendor-collaboration.service';
import { SupplierPortalService } from './services/supplier-portal.service';
import { SupplierPortalController } from './controllers/supplier-portal.controller';
import { SupplierPortalMessage } from './entities/supplier-portal-message.entity';
import { SupplierPortalDocument } from './entities/supplier-portal-document.entity';
import { SupplierPortalInvoice } from './entities/supplier-portal-invoice.entity';
import { SupplierPortalQuote } from './entities/supplier-portal-quote.entity';
import { SupplierPortalCatalogItem } from './entities/supplier-portal-catalog-item.entity';
import { ProcurementQualityController } from './controllers/procurement-quality.controller';
import { ProcurementQualityService } from './services/procurement-quality.service';
import { ProcurementInspection } from './entities/procurement-inspection.entity';
import { ProcurementInspectionTemplate } from './entities/procurement-inspection-template.entity';
import { ProcurementNcr } from './entities/procurement-ncr.entity';

@Module({
  imports: [
    TypeOrmModule.forFeature([
      AuditTrail,
      GoodsReceipt,
      GoodsReceiptItem,
      ProcurementBudget,
      ProcurementCalendarEvent,
      ProcurementNotification,
      PurchaseInvoice,
      PurchaseOrder,
      PurchaseOrderItem,
      PurchaseRequisition,
      PurchaseReturn,
      RFQ,
      RFQBid,
      RFQTemplate,
      SourcingRule,
      VendorContract,
      VendorEvaluation,
      VendorMessage,
      VendorQuotation,
      BomReceipt,
      ProcurementCategory,
      SavingsInitiative,
      VendorScorecard,
      Vendor,
      SourcingStrategy,
      SupplierPortalMessage,
      SupplierPortalDocument,
      SupplierPortalInvoice,
      SupplierPortalQuote,
      SupplierPortalCatalogItem,
      ProcurementInspection,
      ProcurementInspectionTemplate,
      ProcurementNcr,
      ProcurementReportTemplate,
      ProcurementAutomationRule,
      ProcurementRiskAssessment,
      ProcurementComplianceRecord,
      SupplierDiversityProgram,
    ]),
    forwardRef(() => WorkflowModule),
    // EmailService for scheduled reports + automation-rule alerts.
    NotificationsModule,
  ],
  controllers: [
    AuditTrailController,
    BomReceiptController,
    GoodsReceiptController,
    ProcurementBudgetController,
    ProcurementCalendarEventController,
    ProcurementCategoryController,
    ProcurementNotificationController,
    PurchaseInvoiceController,
    SavingsInitiativeController,
    VendorScorecardController,
    PurchaseOrderController,
    PurchaseRequisitionController,
    PurchaseReturnController,
    RFQController,
    RFQBidController,
    RFQTemplateController,
    SourcingIntegrationController,
    VendorCollaborationController,
    VendorContractController,
    VendorEvaluationController,
    VendorPerformanceAnalyticsController,
    VendorQuotationController,
    VendorController,
    SpendAnalysisController,
    ProcurementInsightsController,
    SourcingStrategyController,
    SupplierPortalController,
    ProcurementQualityController,
    ProcurementReportTemplateController,
    ProcurementAutomationRuleController,
    ProcurementRiskAssessmentController,
    ProcurementComplianceRecordController,
    SupplierDiversityProgramController,
  ],
  providers: [
    ApprovalMatrixService,
    ApprovalThresholdSeederService,
    AuditTrailService,
    BomReceiptService,
    ContractService,
    GoodsReceiptService,
    ProcurementBudgetService,
    ProcurementCalendarEventService,
    ProcurementCategoryService,
    ProcurementNotificationService,
    PurchaseInvoiceService,
    SavingsInitiativeService,
    VendorScorecardService,
    PurchaseOrderService,
    PurchaseRequisitionService,
    PurchaseReturnService,
    RFQPolicyService,
    RFQService,
    RFQBidService,
    RFQTemplateService,
    SourcingIntegrationService,
    SpendAnalysisService,
    ProcurementInsightsService,
    ThreeWayMatchingService,
    VendorCollaborationService,
    VendorEvaluationService,
    VendorPerformanceAnalyticsService,
    VendorQuotationService,
    VendorService,
    SourcingStrategyService,
    SupplierPortalService,
    ProcurementQualityService,
    ProcurementReportTemplateService,
    ProcurementAutomationRuleService,
    ProcurementRiskAssessmentService,
    ProcurementComplianceRecordService,
    SupplierDiversityProgramService,
    // Scheduled execution engines (Bull/@Cron).
    ProcurementReportSchedulerService,
    ProcurementAutomationEvaluatorService,
  ],
  exports: [
    ApprovalMatrixService,
    ApprovalThresholdSeederService,
    AuditTrailService,
    BomReceiptService,
    ContractService,
    GoodsReceiptService,
    ProcurementBudgetService,
    ProcurementCalendarEventService,
    ProcurementCategoryService,
    ProcurementNotificationService,
    PurchaseInvoiceService,
    SavingsInitiativeService,
    VendorScorecardService,
    PurchaseOrderService,
    PurchaseRequisitionService,
    PurchaseReturnService,
    RFQPolicyService,
    RFQService,
    RFQBidService,
    RFQTemplateService,
    SourcingIntegrationService,
    SpendAnalysisService,
    ThreeWayMatchingService,
    VendorCollaborationService,
    VendorEvaluationService,
    VendorPerformanceAnalyticsService,
    VendorQuotationService,
    VendorService,
  ],
})
export class ProcurementModule {}
