"""
Django settings for optiforge project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from backend/.env if present (local dev).
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-pni8ntnv+(*dc3^3#3xj1f_%&zhjfvt0sgrsvrr5=vnx8l_(-#')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('true', '1', 't')

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '*').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'optiforge.platform.tenancy',
    'optiforge.platform.identity',
    'optiforge.platform.audit',
    'optiforge.platform.extensions',
    'optiforge.platform.events',
    'optiforge.platform.workflow',
    'optiforge.platform.notifications',
    'optiforge.platform.reporting',
    'optiforge.platform.documents',
    'optiforge.platform.integration',
    'optiforge.platform.api_gateway',
    'optiforge.platform.observability',
    'optiforge.platform.localisation',
    'optiforge.core.sales',
    'optiforge.core.crm',
    'optiforge.core.procurement',
    'optiforge.core.inventory',
    'optiforge.core.project',
    'optiforge.core.hr',
    'optiforge.core.plm',
    'optiforge.core.wms',
    'optiforge.core.it_admin',
    'optiforge.core.sop',
    'optiforge.core.cmms',
    'optiforge.core.ehs',
    'optiforge.core.production_planning',
    'optiforge.core.mes',
    'optiforge.core.finance',
    'optiforge.core.qms',
    'optiforge.core.analytics',
    'optiforge.core.field_service',
    'optiforge.core.commissioning',
    'optiforge.core.logistics',
    'optiforge.core.support',
    'optiforge.modes.eto',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'optiforge.platform.tenancy.middleware.TenantMiddleware',
]

ROOT_URLCONF = 'optiforge.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'optiforge.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

def _db_env(*names, default=None):
    """First present env var. Accepts Django-style DATABASE_* and shared .env DB_* names."""
    for name in names:
        value = os.environ.get(name)
        if value:
            return value
    return default


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': _db_env('DATABASE_NAME', 'DB_DATABASE', default='test_db'),
        'USER': _db_env('DATABASE_USER', 'DB_USERNAME', default='test'),
        'PASSWORD': _db_env('DATABASE_PASSWORD', 'DB_PASSWORD', default='test'),
        'HOST': _db_env('DATABASE_HOST', 'DB_HOST', default='localhost'),
        'PORT': _db_env('DATABASE_PORT', 'DB_PORT', default='5432'),
        'OPTIONS': {
            'sslmode': _db_env(
                'DATABASE_SSLMODE',
                default='require' if _db_env('DB_SSL', default='').lower() == 'true' else 'prefer',
            ),
        },
    }
}

if os.environ.get('DATABASE_URL'):
    import urllib.parse as urlparse
    url = urlparse.urlparse(os.environ['DATABASE_URL'])
    DATABASES['default']['NAME'] = url.path.lstrip('/')
    DATABASES['default']['USER'] = url.username or ''
    DATABASES['default']['PASSWORD'] = url.password or ''
    DATABASES['default']['HOST'] = url.hostname or 'localhost'
    DATABASES['default']['PORT'] = str(url.port) if url.port else '5432'


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# JWT settings
JWT_SECRET = os.environ.get('JWT_SECRET', 'optiforge-dev-secret-change-in-production-32bytes!')

# Django REST Framework defaults.
# Pagination: every ListAPIView / ModelViewSet that doesn't override
# `pagination_class` gets page-number pagination with a 50-item default
# and a 500-item hard cap. Matches NestJS defaults per ADR-0004
# §"Obligations accepted".
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': (
        'optiforge.platform.api_gateway.pagination.DefaultPageNumberPagination'
    ),
    'PAGE_SIZE': 50,
}
